name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements-dev.txt') }}

      - name: Install Tox and any other packages
        run: |
          pip install tox

      - name: Run Tox Tests
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: tox -e py

      - name: Lint
        run: tox -e lint

      - name: Coverage
        run: |
          pip install coveralls pytest pytest-cov requests requests-mock mock
          pytest --cov
          coveralls
